### PR TITLE
Correct examples for git aliases

### PR DESCRIPTION
**Pull request by Tekki**
Syntax is
```
git config --global alias.somealias somecommand
git config --global alias.somealias 'some long command'
```
See https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases.

### CODE REVIEW

**Comment by jhthorsen** [comment]
Thanks! 🎉

**Comment by Tekki** [comment]
I'm assigned to do what?

**Comment by jhthorsen** [comment]
Nothing. I was supposed to merge, but couldn't do it on my phone because of the failing tests. Will merge it now 👍 

(I like assigning PR to the person opening it)

**Comment by Tekki** [comment]
In Mojo::mysql too we regularly have failing tests in a random Perl version.

**Pull request merged**
